name: recipe_meal_planner
description: A new Flutter project.

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  table_calendar: ^3.1.2
  sqflite: ^2.2.2
  path_provider: ^2.0.11
  path: ^1.8.2

flutter:
  assets:
    - assets/images/recipe1.jpg
    - assets/images/recipe2.jpg
    - assets/images/recipe3.jpg
    - assets/images/recipe4.jpg
    - assets/images/courses.jpg
    - assets/images/cuisines.jpg
