name: recipe_meal_planner
description: A new Flutter project for managing recipes and meal plans.

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  table_calendar: ^3.1.2
  provider: ^6.0.0              
  shared_preferences: ^2.0.15    
  sqflite: ^2.4.0
  path_provider: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/recipe1.jpg
    - assets/images/straw.jpg
    - assets/images/lasagna.jpg
    - assets/images/salad.jpg
    - assets/images/pancakes.jpg
    - assets/images/carbonara.jpg
    - assets/images/curry.jpg
    - assets/images/toast.jpg
    - assets/images/cake.jpg
    - assets/images/beef.jpg
    - assets/images/profile.png